### PR TITLE
Auto retrieve plugins + adjust caching

### PR DESCRIPTION
**Pull request by SeanLeRoy**
This change makes `BioImage` automatically retrieve plugin each time it determines which plugin/reader to use.

I made caching an opt-in feature since I am a bit worried about users being confused by cached plugins.

### CODE REVIEW

**Comment by toloudis** [comment]
I wonder if you could just call get_plugins once in __init__.py and just keep that as the cache.  Then just make sure that any additional calls blow away what was there before and completely replace the list.

**Comment by SeanLeRoy** [comment]
> I wonder if you could just call get_plugins once in `__init__.py` and just keep that as the cache. Then just make sure that any additional calls blow away what was there before and completely replace the list.

I think that is the same as what would happen after this changeset. `determine_plugin` is only called once in the `__init__` and the only other time it would be called is if a user explicitly called it as a static method of `BioImage` during which time they could directly supply the cache arg (though I imagine if you are calling it directly it is for some sort of debug purpose in which you would want the cache to be reset each time).

**Comment by toloudis** [comment]
> > I wonder if you could just call get_plugins once in `__init__.py` and just keep that as the cache. Then just make sure that any additional calls blow away what was there before and completely replace the list.
> 
> I think that is the same as what would happen after this changeset. `determine_plugin` is only called once in the `__init__` and the only other time it would be called is if a user explicitly called it as a static method of `BioImage` during which time they could directly supply the cache arg (though I imagine if you are calling it directly it is for some sort of debug purpose in which you would want the cache to be reset each time).

I was actually referring to calling it globally in the bioio package init. (which I guess is invoked the first time you import anything from bioio? or every time?) But I think what you said makes sense, it's kinda the same result.

**Review by toloudis — APPROVED** [review]

**Review by evamaxfield — APPROVED** [review]
Thank you!!

**Pull request merged**
